version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/gui"
      target-branch: "master"
      schedule:
          interval: "daily"
    - package-ecosystem: "gomod"
      directory: "/radicalvpnd"
      target-branch: "master"
      schedule:
          interval: "daily"
