name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Setup Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Gui dependencies
        run: |
          cd gui
          npm ci

      - name: Gui - Code format
        run: |
          cd gui
          npm run format:build

      - name: Gui - Lint
        run: |
          cd gui
          npm run lint

      - name: Gui - Build
        run: |
          cd gui
          npm run build:ci

      - name: Daemon - Code format
        run: |
          cd radicalvpnd
          gofmt -s -w .
          git diff --relative --exit-code

      - name: Daemon - Build
        run: |
          cd radicalvpnd
          go build .
