name: RadicalVPN Desktop Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.20
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Setup Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Prettier Code Formatting
        run: |
          cd gui
          npm ci
          npm run format:build

      - name: Build App
        run: |
          build\windows\build-windows.bat

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: radicalvpn-win-0.0.1.exe
          path: build/windows/bin/RadicalVPN-Setup.exe

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.20
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Setup Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install build dependencies
        run: brew install autoconf automake libtool

      - name: Install the Apple Developer Certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_DEVELOPER_ID_CERT }}
          P12_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_CERT_PASSWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secret
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Prettier Code Formatting
        run: |
          cd gui
          npm ci
          npm run format:build

      - name: Build App
        env:
          TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
        run: |
          chmod +x ./build/darwin/build.sh
          ./build/darwin/build.sh -c $TEAM_ID

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: radicalvpn-darwin-0.0.1.dmg
          path: build/darwin/_compiled/RadicalVPN.dmg
