name: Run Gosec
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gosec:
    name: GoSec Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install GoSec 2.18.2
        run: |
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.18.2

      - name: Run Gosec Security Scanner
        run: |
          cd radicalvpnd
          gosec -exclude=G114,G304,G302 ./...
