name: Nightly Build

on:
  schedule:
    # triggers every day at 2PM UTC
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  build_nightly_windows:
    runs-on: windows-latest
    name: Build Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache-dependency-path: |
            radicalvpnd/go.sum

      - name: Setup Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Build App
        run: |
          build\windows\build-windows.bat

      - name: Rename Artifact
        working-directory: build/windows/bin/
        run: |
          ren RadicalVPN-Setup.exe radicalvpn-win.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_windows
          path: build/windows/bin/radicalvpn-win.exe

  build_nightly_macos:
    runs-on: macos-latest
    name: Build MacOS
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache-dependency-path: |
            radicalvpnd/go.sum

      - name: Setup Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install build dependencies
        run: brew install autoconf automake libtool

      - name: Install the Apple Developer Certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_DEVELOPER_ID_CERT }}
          P12_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_CERT_PASSWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secret
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Build App
        env:
          TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
        run: |
          chmod +x ./build/darwin/build.sh
          ./build/darwin/build.sh -c $TEAM_ID

      - name: Rename Artifact
        working-directory: build/darwin/_compiled/
        run: |
          mv RadicalVPN.dmg radicalvpn-darwin.dmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_darwin
          path: build/darwin/_compiled/radicalvpn-darwin.dmg

  prepare_nightly:
    runs-on: ubuntu-latest
    name: Prepare Nightly
    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}
    needs: [build_nightly_windows, build_nightly_macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update nightly tag
        uses: EndBug/latest-tag@9071b46e28bb944c47293dcefa47fab3c5469314
        with:
          ref: nightly

      - name: Generate Commit Hash
        id: var
        run: |
          echo "full_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  publish_nightly:
    runs-on: ubuntu-latest
    name: Publish Nightly
    needs: [prepare_nightly]
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4

      - name: Copy artifacts
        run: |
          cp -r build_*/* .
          rm -rf build_*

      - name: Get artifact checksums
        id: get_artifact_checksums
        run: |
          echo "artifact_checksums<<EOF" >> $GITHUB_OUTPUT
          sha256sum * >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly
          tag_name: nightly
          prerelease: true
          body: |
            **This Pre-release has been built by Github Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Build Hashes (SHA-256):
            ```
            ${{ steps.get_artifact_checksums.outputs.artifact_checksums }}
            ```

            Important: This is not a stable release.
            We do not recommend using this in a production environment.

            No warranty is provided for this type of release.
            Please report any issues you find to our issue tracker.

            These releases should be used for the following purposes:
            - Testing new features
            - Testing bug fixes
            - Other testing or development purposes

            Full Commit Hash:
            ```
            ${{ needs.prepare_nightly.outputs.full_sha }}
            ```
          files: |
            *
