name: Nightly Build

on:
  schedule:
    # triggers every day at 2PM UTC
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  build_nightly_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Setup Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Build App
        run: |
          build\windows\build-windows.bat

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/windows/bin/RadicalVPN-Setup.exe

  build_nightly_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Setup Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install build dependencies
        run: brew install autoconf automake libtool

      - name: Install the Apple Developer Certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_DEVELOPER_ID_CERT }}
          P12_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_CERT_PASSWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secret
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Build App
        env:
          TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
        run: |
          chmod +x ./build/darwin/build.sh
          ./build/darwin/build.sh -c $TEAM_ID

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/darwin/_compiled/RadicalVPN.dmg

  update_nightly_tag:
    runs-on: ubuntu-latest
    needs: [build_nightly_windows, build_nightly_macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update nightly tag
        uses: EndBug/latest-tag@9071b46e28bb944c47293dcefa47fab3c5469314
        with:
          ref: nightly

  publish_nightly:
    runs-on: ubuntu-latest
    needs: [update_nightly_tag]
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          name: Nightly
          tag_name: nightly
          prerelease: true
